import type { Metadata } from "next";
import { Hanken_Grotesk } from "next/font/google";
import Breadcrumb from "./components/Navbar/Breadcrumb";
import "./layout.css";

const fontFamily = Hanken_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fontFamily.className}>
        <Breadcrumb />
        {children}
      </body>
    </html>
  );
}
